package org.backend.molsys.testrequests;

import lombok.Data;

import java.time.LocalDateTime;

@Data
public class CreateTestRequest {

    private String service;
//    private String category; // Added category
    private String quantity;
    private String amountOfData;
    private String isolation;
    private String analysis;
    private LocalDateTime updated;
//    private String userName; // Added userName
//    private String address;
//    private String email;
//    private String phoneNumber;
//    private Integer pinCode;

    // Constructors, getters, and setters can be generated by the lombok @Data annotation

    public void getAnalysis(String no) {
        // Your implementation for getAnalysis
    }

    public void getIsolation(String yes) {
        // Your implementation for getIsolation
    }

}
