package org.backend.molsys.testrequests;

public enum RequestStatus {

    INITIATED,SALES_REVIEW_IN_PROGRESS,SALES_REVIEW_COMPLETED,LAB_TEST_IN_PROCESS,ANALYSIS_IN_PROCESS,COMPLETED
//    INITIATED,SALES_REVIEW_IN_PROGRESS,SALES_REVIEW_COMPLETED,DIAGNOSIS_IN_PROCESS,COMPLETED
}

